api/urls.py
from django.urls import path
from .views.index import index
from .views.social_view import SocialView
from .views.get_social import GetSocial

urlpatterns = [
    path("", index),
    path("social", SocialView.as_view()),
    path("get-social", GetSocial.as_view()),
]

personal_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
    path("", include("personalpage.urls")),
    path("api/", include("api.urls")),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

personalpage/urls.py
from django.urls import path
from .views.index import IndexView
from .views.contacts import ContactsView

app_name = "personalpage"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("contacts", ContactsView.as_view(), name="contacts"),
]

api/models.py
from django.db.models import Model, CharField, DateTimeField
from django.contrib import admin

# Create your models here.
class Social(Model):
    social_choices = (
        ("facebook", "facebook"),
        ("github", "github"),
        ("twitter", "twitter"),
        ("discord", "discord"),
        ("linkedin", "linkedin"),
        ("reddit", "reddit"),
        ("email", "email"),
    )

    social_map = {
        "facebook": {
            "url": "https://facebook.com/",
            "fa": "fa-brands fa-facebook",
        },
        "github": {
            "url": "https://github.com/",
            "fa": "fa-brands fa-github",
        },
        "twitter": {
            "url": "https://twitter.com/",
            "fa": "fa-brands fa-twitter",
        },
        "discord": {
            "url": "https://discordapp.com/users/",
            "fa": "fa-brands fa-discord",
        },
        "linkedin": {
            "url": "https://linkedin.com/in/",
            "fa": "fa-brands fa-linkedin-in",
        },
        "reddit": {
            "url": "https://reddit.com/user/",
            "fa": "fa-brands fa-reddit",
        },
        "email": {
            "url": "mailto:",
            "fa": "fa-solid fa-envelope",
        },
    }

    social_name = CharField(
        max_length=100,
        unique=True,
        null=False,
        blank=False,
        choices=social_choices,
    )
    username = CharField(max_length=100, null=False, blank=False)
    created_at = DateTimeField(auto_now_add=True, null=False, blank=False)

    def __str__(self) -> str:
        url = self.social_map[self.social_name]["url"] + self.username
        return url

    def social_url(self) -> str:
        return str(self)

    def social_fa(self):
        return self.social_map[self.social_name]["fa"]

api/views/get_social.py
from rest_framework.views import APIView
from ..serializers.social_serializer import SocialSerializer
from ..models import Social
from rest_framework.response import Response
from rest_framework import status


class GetSocial(APIView):
    serializer_class = SocialSerializer
    lookup_url_kwarg = "social_name"

    def get(self, request, format=None):
        social_name = request.GET.get(self.lookup_url_kwarg)

        if social_name != None:
            social = Social.objects.filter(social_name=social_name)

            if len(social) > 0:
                data = SocialSerializer(social[0]).data
                return Response(data, status=status.HTTP_200_OK)

            return Response(
                {"Social not found": f"Invalid social_name: {social_name}"},
                status=status.HTTP_404_NOT_FOUND,
            )

        return Response(
            {"Bad Request": "social_name parameter not found in request"},
            status=status.HTTP_400_BAD_REQUEST,
        )

api/views/index.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Api index page")

api/views/social_view.py
from rest_framework import generics
from rest_framework.views import APIView
from ..models import Social
from ..serializers.social_serializer import SocialSerializer


class SocialView(generics.ListAPIView):
    queryset = Social.objects.all()
    serializer_class = SocialSerializer

personalpage/views/contacts.py
from .views import TemplateView
from django.shortcuts import render
from api.models import Social
from django.http import HttpRequest, HttpResponse


class ContactsView(TemplateView):
    title = "ajauniskis Contacts"
    template_name = "contacts.html"

    socials = Social.objects.all()

    def get(self, request: HttpRequest) -> HttpResponse:
        # updateparams.delay()
        context = {
            "title": "Contact Me",
            "socials": self.socials,
        }
        return render(request, self.template_name, context)

personalpage/views/index.py
from .views import TemplateView


class IndexView(TemplateView):
    title = "ajauniskis page"
    template_name = "index.html"

personalpage/views/views.py
from django.views.generic import TemplateView as tw


class TemplateView(tw):
    title = ""

    def get_title(self) -> str:
        return self.title

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["title"] = self.get_title()
        return context

personalpage/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% load static %}
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
</head>
<body>
    {% include "base/navbar.html" %}
    <div class="container">Base placeholder</div>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    {% include "base/footer.html" %}
</body>

personalpage/templates/base/footer.html
<footer class="bd-footer mt-1 bg-dark fixed-bottom text-white-50">
  <div class="container">
      <div class="row">
          <p class="text-center">
              &copy; {% now "Y" %} <a href="https://github.com/ajauniskis/personal-website" class="text-reset">@github.com</a>
          </p>
      </div>
    </div>
</footer>

personalpage/templates/base/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'navbrand.png' %}" alt="" width="50" height="50" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'index' %}active{% endif %}" aria-current="page" href="{% url 'personalpage:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="modal" data-bs-target="#contactsModal" onclick="get_contacts_modal()">Contacts</a>
          <div class="modal fade" id="contactsModal" tabindex="-1" role="dialog" aria-labelledby="contactsModalLabel" aria-hidden="true">
            <div class="modal-dialog" id="contacts_modal">
              <!-- Modal from contacts.html-->
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script>
  function get_contacts_modal() {
    $.ajax({
      url:"/contacts",
      type: "GET",
      data: {},
      async: true,
      beforeSend: function(){
        $('#contacts_modal').html('Loading..');
      },
      success:function(result){
        $('#contacts_modal').html(result);
      }
    })
  }
</script>

personalpage/templates/contacts.html
<!-- Modal -->
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title" id="contactsModalLabel">{{ title }}</h4>
    </div>
    <div class="modal-body">
        {% if socials.count < 1 %}
        <p>Sorry, no contacts for now &#128546;</p>
        {% else %}
            {% for social in socials %}
                <ul>
                    <h5>
                        <i class="{{ social.social_fa }}"></i> <a href={{ social.social_url }}>{{ social.social_name }}</a>
                    </h5>
                </ul>
            {% endfor %}
        {% endif %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
    </div>
</div>

personalpage/templates/index.html
<!DOCTYPE html>
{% extends 'base/base.html' %}
    {% block body_block %}
        <h1>Index page</h1>
        <p>Testing fa <i class="fa-brands fa-github"></i></p>
    {% endblock %}